-- Reference DDL for zephyr-booking-confirmation-service (Oracle).
-- Provisioned externally (no Flyway/Liquibase), mirroring the publisher service.
--
-- Inbox = store-and-forward landing table for consumed internal.<region> messages.
-- Outbox = staged events to publish to published.<region>.
-- Scheduled pollers need no coordination lock: each drain claims rows with FOR UPDATE SKIP LOCKED,
-- so concurrent pollers on different instances take disjoint rows.

CREATE TABLE BOOKING_CONFIRMATION_INBOX (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGION            VARCHAR2(8)   NOT NULL,          -- AMER | APAC | EMEA
    IDEMPOTENCY_KEY   VARCHAR2(512) NOT NULL,
    SOURCE_TOPIC      VARCHAR2(255) NOT NULL,
    KAFKA_PARTITION   NUMBER,
    KAFKA_OFFSET      NUMBER,
    MESSAGE_KEY       VARCHAR2(512),
    TRACE_ID          VARCHAR2(64),                    -- correlation id from the event body ($.traceId)
    HEADERS           CLOB,                            -- inbound headers as JSON (optional)
    RAW_PAYLOAD       CLOB          NOT NULL,          -- pivot JSON as received
    PROCESSING_STATUS VARCHAR2(32)  NOT NULL,          -- NEW | PROCESSED | AGGREGATED | PROCESS_FAILURE | INGEST_FAILURE | INVALID
    RETRY_COUNT       NUMBER        DEFAULT 0 NOT NULL,
    ERROR_MESSAGE     CLOB,
    RECEIVED_ON       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_ON        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_INBOX_DEDUPE UNIQUE (REGION, IDEMPOTENCY_KEY)
);
CREATE INDEX IX_INBOX_DRAIN ON BOOKING_CONFIRMATION_INBOX (PROCESSING_STATUS, REGION, ID);

CREATE TABLE BOOKING_CONFIRMATION_OUTBOX (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGION            VARCHAR2(8)   NOT NULL,
    IDEMPOTENCY_KEY   VARCHAR2(512) NOT NULL,
    DESTINATION       VARCHAR2(255) NOT NULL,          -- published.<region> topic
    MESSAGE_KEY       VARCHAR2(512),
    KAFKA_PARTITION   NUMBER,                          -- carried from the inbox row; ordering/parallelism unit (ADR 0001)
    TRACE_ID          VARCHAR2(64),                    -- correlation id propagated from the inbox
    EVENT_PAYLOAD     CLOB          NOT NULL,          -- serialized event payload
    HEADERS           CLOB,
    PROCESSING_STATUS VARCHAR2(32)  NOT NULL,          -- NEW | SENT | SEND_FAILURE | RETRY_EXHAUSTED
    RETRY_COUNT       NUMBER        DEFAULT 0 NOT NULL,
    ERROR_MESSAGE     CLOB,
    INBOX_ID          NUMBER,                          -- provenance
    CREATED_ON        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_ON        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
-- Partition included ahead of ID so a partition-scoped relay drain (ADR 0001) stays index-ordered.
CREATE INDEX IX_OUTBOX_DRAIN ON BOOKING_CONFIRMATION_OUTBOX (PROCESSING_STATUS, REGION, KAFKA_PARTITION, ID);
-- Head-of-line per key (ADR 0001): the RELAY drain skips a NEW row while an earlier same-key row is unsent.
-- PROCESSING_STATUS trails so the NOT EXISTS gate is answered index-only (no table hop per candidate row).
CREATE INDEX IX_OUTBOX_KEY_ORDER ON BOOKING_CONFIRMATION_OUTBOX (REGION, MESSAGE_KEY, ID, PROCESSING_STATUS);
