-- Reference DDL for zephyr-booking-confirmation-service (Oracle).
-- Provisioned externally (no Flyway/Liquibase), mirroring the publisher service.
--
-- Inbox = store-and-forward landing table for consumed internal.<region> messages.
-- Outbox = staged events to publish to published.<region>.
-- Region lock = per-region.processType distributed lock for the scheduled pollers.

CREATE TABLE BOOKING_CONFIRMATION_INBOX (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGION            VARCHAR2(8)   NOT NULL,          -- AMER | APAC | EMEA
    IDEMPOTENCY_KEY   VARCHAR2(512) NOT NULL,
    SOURCE_TOPIC      VARCHAR2(255) NOT NULL,
    KAFKA_PARTITION   NUMBER,
    KAFKA_OFFSET      NUMBER,
    MESSAGE_KEY       VARCHAR2(512),
    EVENT_TYPE        VARCHAR2(16),                    -- CREATED | AMENDED | DELETED (set in PROCESS once parsed)
    TRACE_ID          VARCHAR2(64),                    -- correlation id from the event body ($.traceId)
    HEADERS           CLOB,                            -- inbound headers as JSON (optional)
    RAW_PAYLOAD       CLOB          NOT NULL,          -- pivot JSON as received
    -- NEW | PROCESSED | AGGREGATED | BLOCKED | SUPERSEDED | PROCESS_FAILURE | PARKED | INVALID
    PROCESSING_STATUS VARCHAR2(32)  NOT NULL,
    RETRY_COUNT       NUMBER        DEFAULT 0 NOT NULL,
    NEXT_ATTEMPT_AT   TIMESTAMP,                       -- backoff gate for PROCESS_FAILURE requeue (null = ready)
    ERROR_MESSAGE     CLOB,
    RECEIVED_ON       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_ON        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_INBOX_DEDUPE UNIQUE (REGION, IDEMPOTENCY_KEY)
);
CREATE INDEX IX_INBOX_DRAIN ON BOOKING_CONFIRMATION_INBOX (PROCESSING_STATUS, REGION, ID);
-- Release-by-trade lookups (flip BLOCKED -> NEW once a key's CREATE is SENT).
CREATE INDEX IX_INBOX_KEY ON BOOKING_CONFIRMATION_INBOX (REGION, MESSAGE_KEY, PROCESSING_STATUS);

CREATE TABLE BOOKING_CONFIRMATION_OUTBOX (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGION            VARCHAR2(8)   NOT NULL,
    IDEMPOTENCY_KEY   VARCHAR2(512) NOT NULL,
    DESTINATION       VARCHAR2(255) NOT NULL,          -- published.<region> topic
    MESSAGE_KEY       VARCHAR2(512),
    EVENT_TYPE        VARCHAR2(16),                    -- CREATED | AMENDED | DELETED (drives the create-barrier gate)
    TRACE_ID          VARCHAR2(64),                    -- correlation id propagated from the inbox
    EVENT_PAYLOAD     CLOB          NOT NULL,          -- serialized event payload
    HEADERS           CLOB,
    -- NEW | SENT | SEND_FAILURE | PARKED | SUPERSEDED  (PARKED = retained/alerted/replayable; SUPERSEDED = parked CREATE retired by a promoted AMEND)
    PROCESSING_STATUS VARCHAR2(32)  NOT NULL,
    RETRY_COUNT       NUMBER        DEFAULT 0 NOT NULL,
    NEXT_ATTEMPT_AT   TIMESTAMP,                       -- backoff gate for SEND_FAILURE requeue (null = ready)
    ERROR_MESSAGE     CLOB,
    INBOX_ID          NUMBER,                          -- provenance
    CREATED_ON        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_ON        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IX_OUTBOX_DRAIN ON BOOKING_CONFIRMATION_OUTBOX (PROCESSING_STATUS, REGION, ID);

CREATE TABLE BOOKING_CONFIRMATION_REGION_LOCK (
    LOCK_KEY        VARCHAR2(32) PRIMARY KEY,          -- e.g. AMER.RELAY
    LOCKED_BY       VARCHAR2(255) NOT NULL,
    LOCKED_AT       TIMESTAMP     NOT NULL,
    LOCK_EXPIRES_AT TIMESTAMP     NOT NULL
);

-- Create-barrier ledger: per-trade memory of whether the downstream third party has been told
-- a trade exists yet. The third party REJECTS an AMEND/DELETE whose CREATE it never received, so an
-- AMEND must never be relayed before its CREATE reaches SENT. One row per (region, message key).
--
--   NONE       no CREATE seen yet for this key
--   IN_FLIGHT  a CREATE has been staged to the outbox but is not yet SENT (amendments wait)
--   SENT       a CREATE has been delivered downstream (amendments may flow)
--   FAILED     the CREATE failed terminally (INVALID/PARKED) — a waiting AMEND is auto-promoted
--   VOID       the trade was deleted before any CREATE was emitted — emit nothing
CREATE TABLE BOOKING_CONFIRMATION_TRADE_GATE (
    REGION       VARCHAR2(8)   NOT NULL,
    MESSAGE_KEY  VARCHAR2(512) NOT NULL,
    CREATE_STATE VARCHAR2(16)  NOT NULL,               -- NONE | IN_FLIGHT | SENT | FAILED | VOID
    UPDATED_ON   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TRADE_GATE PRIMARY KEY (REGION, MESSAGE_KEY)
);
